import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';import'./styles.css';
const API='/api';
type Product={id:string;name:string;description:string;credit_cost:number};
const samplePlates=['TST0A00','DEV1B11','MOCK2C22'];
function Brand(){return <div className="brand"><div className="mark">C</div><div><strong>CARPIVARA</strong><span>consulta veicular inteligente</span></div></div>}
function App(){const[token,setToken]=useState(localStorage.getItem('token')||'');const[user,setUser]=useState<any>(null);const[balance,setBalance]=useState(0);const[products,setProducts]=useState<Product[]>([]);const[plate,setPlate]=useState('TST0A00');const[productId,setProductId]=useState('COMPLETE');const[result,setResult]=useState<any>(null);const[history,setHistory]=useState<any[]>([]);const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[sandbox,setSandbox]=useState(false);
 const api=async(path:string,opt:any={})=>{const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opt.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');return j};
 const refresh=async()=>{if(!token)return;try{const[m,p,h]=await Promise.all([api('/me'),api('/query-products'),api('/queries')]);setUser(m.user);setBalance(m.balance);setSandbox(Boolean(m.sandbox));setProducts(p);setHistory(h);}catch{localStorage.removeItem('token');setToken('')}};
 useEffect(()=>{refresh()},[token]);
 const selected=useMemo(()=>products.find(p=>p.id===productId),[products,productId]);
 const login=async(e:any)=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});const j=await r.json();if(!r.ok)throw new Error(j.error||'LOGIN_FAILED');localStorage.setItem('token',j.token);setToken(j.token)}catch(e:any){setError(e.message)}};
 const query=async()=>{setLoading(true);setError('');setResult(null);try{const j=await api('/queries',{method:'POST',body:JSON.stringify({plate,productId})});setResult(j.result);await refresh()}catch(e:any){setError(e.message);await refresh()}finally{setLoading(false)}};
 const buy=async()=>{try{await api('/payments/sandbox',{method:'POST',body:JSON.stringify({credits:50})});await refresh()}catch(e:any){setError(e.message)}};
 if(!token)return <div className="loginShell"><div className="loginCopy"><Brand/><h1>Descubra o histórico antes de decidir.</h1><p>Uma plataforma simples para consultar dados, débitos e restrições veiculares em um único relatório.</p><div className="trustLine"><span>Consulta rápida</span><span>Histórico salvo</span><span>Dados organizados</span></div></div><form className="loginCard" onSubmit={login}><div className="eyebrow">Acesso à plataforma</div><h2>Entrar</h2><label>E-mail<input name="email" defaultValue="cliente@demo.local" autoComplete="email"/></label><label>Senha<input name="password" type="password" defaultValue="Demo@123456" autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button className="primary">Entrar</button>{sandbox&&null}<small>Ambiente inicial de validação com dados fictícios.</small></form></div>;
 return <div className="app"><aside><Brand/><nav><a className="active">Nova consulta</a><a>Histórico</a><a>Carteira</a><a>Relatórios</a></nav><div className="asideFoot"><span>{sandbox?'SANDBOX':'PRODUÇÃO'}</span><button onClick={()=>{localStorage.removeItem('token');setToken('')}}>Sair</button></div></aside><main><header><div><p className="eyebrow">Visão geral</p><h1>Consulta veicular</h1></div><div className="account"><div><span>Olá, {user?.name}</span><strong>{balance} créditos</strong></div>{sandbox&&<button className="soft" onClick={buy}>+ 50 créditos teste</button>}</div></header><section className="queryPanel"><div><p className="eyebrow">Nova consulta</p><h2>Digite a placa do veículo</h2><p className="muted">Escolha o nível de consulta. O resultado fica salvo automaticamente no histórico.</p></div><div className="queryControls"><label>Placa<input value={plate} onChange={e=>setPlate(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,''))} maxLength={7}/></label><label>Consulta<select value={productId} onChange={e=>setProductId(e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="cost"><span>Custo</span><strong>{selected?.credit_cost??'—'} créditos</strong></div><button className="primary" onClick={query} disabled={loading}>{loading?'Consultando…':'Consultar veículo'}</button></div>{sandbox&&<div className="samples">Placas de teste: {samplePlates.map(x=><button key={x} onClick={()=>setPlate(x)}>{x}</button>)}</div>}{error&&<div className="error">{translateError(error)}</div>}</section>{result?<Report r={result}/>:<section className="empty"><div className="emptyIcon">✓</div><h2>O relatório aparecerá aqui</h2><p>Débitos, restrições, identificação e demais dados serão organizados em blocos claros para facilitar a decisão.</p></section>}<section className="history"><div className="sectionHead"><div><p className="eyebrow">Histórico</p><h2>Consultas recentes</h2></div><span>{history.length} registros</span></div><div className="historyTable">{history.length===0?<p className="muted">Nenhuma consulta realizada.</p>:history.slice(0,8).map(h=><div className="historyRow" key={h.id}><strong>{h.plate}</strong><span>{h.product_id}</span><span>{new Date(h.created_at).toLocaleString('pt-BR')}</span><b className={h.status==='SUCCESS'?'good':'neutral'}>{h.status==='SUCCESS'?'Concluída':h.status}</b><span>{h.credits_cost} cr.</span></div>)}</div></section></main></div>}
function translateError(e:string){return({INVALID_PLATE:'Placa inválida.',INSUFFICIENT_CREDITS:'Saldo insuficiente.',PLACA_NAO_ENCONTRADA_SANDBOX:'Placa não encontrada no ambiente de testes.'}as any)[e]||e}
function Report({r}:{r:any}){const money=(c:number)=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const total=r.debts.reduce((s:number,d:any)=>s+d.amountCents,0);const alerts=r.restrictions.filter((x:any)=>x.alert).length;return <section className="report"><div className="reportTop"><div><div className="successPill">Consulta concluída</div><h2>{r.identification.fullModel||r.identification.model}</h2><p>{r.characteristics.manufactureYear}/{r.characteristics.modelYear} · {r.characteristics.color} · {r.characteristics.fuel}</p></div><div className="plate">{r.identification.plate}</div></div><div className="summary"><div><span>Situação</span><strong>{r.registration.status||'Não informado'}</strong></div><div><span>Débitos mapeados</span><strong>{money(total)}</strong></div><div><span>Alertas</span><strong>{alerts}</strong></div><div><span>Localidade</span><strong>{r.registration.city}/{r.registration.state}</strong></div></div><div className="reportGrid"><Info title="Identificação" rows={[['Marca',r.identification.brand],['Modelo',r.identification.model],['Renavam',r.identification.renavam],['Chassi',r.identification.chassis],['Motor',r.identification.engine],['Câmbio',r.identification.gearbox]]}/><Info title="Características" rows={[['Categoria',r.characteristics.category],['Tipo',r.characteristics.type],['Espécie',r.characteristics.species],['Potência',r.characteristics.power],['Cilindrada',r.characteristics.displacement],['Procedência',r.characteristics.origin]]}/><div className="resultCard"><h3>Débitos</h3>{r.debts.map((d:any)=><div className="dataRow" key={d.key}><span>{d.label}</span><strong className={d.hasDebt?'attention':''}>{money(d.amountCents)}</strong></div>)}</div><div className="resultCard"><h3>Restrições</h3>{r.restrictions.map((x:any)=><div className="restriction" key={x.key}><div><strong>{x.label}</strong><span>{x.status}</span></div><b className={x.alert?'alertDot':'okDot'}>{x.alert?'!':'✓'}</b></div>)}</div></div></section>}
function Info({title,rows}:{title:string;rows:any[]}){return <div className="resultCard"><h3>{title}</h3>{rows.map(([a,b])=><div className="dataRow" key={a}><span>{a}</span><strong>{b||'—'}</strong></div>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
